name: Pull Talawa Changes

on:
  schedule:
    - cron: '0 1 * * *' # Runs every Sunday at 1:00AM UTC
  workflow_dispatch:

jobs:
  pull_talawa_mobile:
    name: Pull Talawa Mobile Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.email "${{ env.email }}"
          git config --global user.name "${{ github.actor }}"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      - name: Run bash script to fetch Talawa mobile docs
        run: bash .github/workflows/pull-talawa-mobile-docs.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  pull_talawa_api_admin:
    name: Pull Talawa API and Admin Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.email "${{ env.email }}"
          git config --global user.name "${{ github.actor }}"

      - name: Run bash script for docs API
        run: bash .github/workflows/pull-docs-api.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run bash script for docs admin
        run: bash .github/workflows/pull-docs-admin.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
