const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'introduction' }],
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },

    {
      type: 'category',
      label: 'Developer Resources',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'developers/introduction' },
        {
          type: 'category',
          label: 'Talawa API',
          link: {
            type: 'generated-index',
          },
          collapsed: true,
          items: [
            'developers/talawa-api/api-overview',
            'developers/talawa-api/api-design-guide',
            'developers/talawa-api/api-error-handling-guide',
            {
              type: 'category',
              label: 'Base Constraints',
              link: {
                type: 'generated-index',
              },
              collapsed: true,
              items: [
                'developers/talawa-api/constraints/user',
                'developers/talawa-api/constraints/organization',
                'developers/talawa-api/constraints/admin',
              ],
            },
            'developers/talawa-api/mutations',
            'developers/talawa-api/schemas',
            'developers/talawa-api/authentication',
            'developers/talawa-api/functionality',
            'developers/talawa-api/pagination',
            'developers/talawa-api/expectations',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Requirements Docs',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Existing Features',
          link: {
            type: 'generated-index',
          },
          collapsed: true,
          items: [
            'functionalities/core-functionalities',
            'functionalities/recurring-events',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'UI/UX Design',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'design' }],
    },
  ],
};

module.exports = sidebars;
