const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'introduction' }],
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },

    {
      type: 'category',
      label: 'Developer Resources',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'developers/introduction' }],
    },
    {
      type: 'category',
      label: 'UI/UX Design',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'design' }],
    },
  ],
};

module.exports = sidebars;
