contact_links:
    - name: 📃 Admin Panel Issue
      url: https://github.com/PalisadoesFoundation/talawa-admin/issues/new/choose
      about: This issue tracker is not for Admin Panel issues. Please file Admin Panel issues here.
    - name: 🤔 Questions and Help
      url: https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-2e75w7ups-AVCObKnnHqNzd76CmIRyag
      about: This issue tracker is not for support questions. Please refer to the Slack community's help and discussion forums.
