/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Talawa Project Documentation",
  "tagline": "Open Source Software for Managing Community Based Organizations",
  "url": "https://docs.talawa.io",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "deploymentBranch": "gh-pages",
  "organizationName": "PalisadoesFoundation",
  "projectName": "talawa-docs",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\Salil\\Desktop\\talawa-docs\\sidebars.js"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/PalisadoesFoundation/talawa-docs/tree/develop/docs"
        },
        "theme": {
          "customCss": "C:\\Users\\Salil\\Desktop\\talawa-docs\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "Talawa",
      "logo": {
        "alt": "Talawa Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "to": "docs/",
          "activeBasePath": "docs",
          "label": "About",
          "position": "left"
        },
        {
          "href": "https://docs.talawa.io/talawa/index.html",
          "target": "_self",
          "label": "Talawa",
          "position": "left"
        },
        {
          "href": "https://docs.talawa.io/talawa-api/schema/index.html",
          "target": "_self",
          "label": "Talawa Api",
          "position": "left"
        },
        {
          "href": "https://github.com/PalisadoesFoundation",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Community",
          "items": [
            {
              "label": " Slack",
              "to": "https://github.com/PalisadoesFoundation/talawa#readme",
              "className": "footer__icon footer__slack"
            },
            {
              "label": " Twitter",
              "to": "https://twitter.com/palisadoesorg?lang=en",
              "className": "footer__icon footer__twitter"
            },
            {
              "label": " Facebook",
              "to": "https://www.facebook.com/palisadoesproject/",
              "className": "footer__icon footer__facebook"
            },
            {
              "label": " Instagram",
              "to": "https://www.instagram.com/palisadoes/?hl=en",
              "className": "footer__icon footer__instagram"
            },
            {
              "label": " News",
              "to": "/docs/features/news%20feed/news-feed-overview",
              "className": "footer__icon footer__news"
            },
            {
              "label": " Contact Us",
              "to": "https://www.palisadoes.org/contact/",
              "className": "footer__icon footer__contact"
            }
          ]
        },
        {
          "title": "Development",
          "items": [
            {
              "label": " GitHub",
              "to": "https://github.com/PalisadoesFoundation",
              "className": "footer__icon footer__github"
            },
            {
              "label": " Opportunities",
              "to": "/docs/internships/internship-ideas",
              "className": "footer__icon footer__opportunities"
            },
            {
              "label": " Team",
              "to": "/docs/features/members/members-overview",
              "className": "footer__icon footer__team"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 My Project, Inc. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
