name: Pull Request Review

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pull-request-review:
    uses: PalisadoesFoundation/.github/.github/workflows/pull-request-review.yml@main
    secrets: inherit
