name: Pull Talawa Mobile Changes

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.email "${{ env.email }}"
          git config --global user.name "${{ github.actor }}"
      
      - name: Run bash script to fetch Talawa mobile docs
        run: bash .github/workflows/pull-docs-talawa.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
