name: Pull Talawa API Changes

on:
  schedule:
    - cron: '0 0 * * 0' 

jobs:
  pull:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.email "${{ env.email }}"
          git config --global user.name "${{ github.actor }}"
      
      - name: Run bash script
        run: |
          bash .github/workflows/pull-docs.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
