name: Pull Request Target

on:
  pull_request_target:
    types: [opened]

jobs:
  pull-request-target:
    uses: PalisadoesFoundation/.github/.github/workflows/pull-request-target.yml@main
    secrets: inherit
